### ISSUE TITLE
Could you publish the unigame.localization model ?

### ISSUE THREAD

**Issue by liuxinjia** [UnioGame/UniGame.ViewSystem#32]
For some reason, I can't install it under the help of the Unity package manager. I try to manually install the required module from your organization pages, but there is no "com.unigame.localization" package.🤣
<img width="402" alt="image" src="https://user-images.githubusercontent.com/24849085/165116279-6407c370-fd79-46a4-af42-31aa6e30bb4a.png">

Could you pls help me solve this problem. Thank it advanced!!! /😁😁😁

**Comment by Mefodei** [comment]
Well, i will try to fix that asap. Thx you
